language: go
go:
    - "1.15"
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
allow_failures:
    - os: windows
matrix:
    include:
    -   os: linux
        script:
            - go test -v -covermode=count -coverprofile=coverage.out
        after_script:
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
